<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH29688k\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH29688k/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH29688k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH29688k\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH29688k\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H29688k',
    'container.build_id' => '0415602f',
    'container.build_time' => 1583321491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH29688k');
