<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVktM41N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVktM41N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVktM41N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVktM41N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVktM41N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VktM41N',
    'container.build_id' => '36421399',
    'container.build_time' => 1583483788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVktM41N');
